# Generated by Django 2.2.6 on 2019-10-31 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_passedpoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='passedpoll',
            name='score',
            field=models.FloatField(default=0.1),
            preserve_default=False,
        ),
    ]
