# Generated by Django 2.2.6 on 2019-10-31 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_passedpoll_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passedpoll',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
