# Generated by Django 2.2.6 on 2019-10-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
