# Generated by Django 2.2.6 on 2019-10-31 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_answeredquestion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answeredquestion',
            old_name='poll',
            new_name='passed_poll',
        ),
    ]
